name: getx_exten
description: A new Flutter package with GetListener and GetConsumer for Getx Lovers
version: 1.0.0
homepage: https://github.com/edkluivert/getx_exten
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
 flutter:
  sdk: flutter
 get: ^4.6.6


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  flutter_test:
   sdk: flutter
